<?php 
namespace Vexsoluciones\Checkout\Setup;

use Magento\Framework\Module\Setup\Migration;
use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;


class InstallData implements InstallDataInterface
{

    private $departamentoFactory;
    private $provinciaFactory;
    private $distritoFactory;
    

    public function __construct(
        \Vexsoluciones\Checkout\Model\DepartamentoFactory $departamento,
        \Vexsoluciones\Checkout\Model\ProvinciaFactory $provincia,
        \Vexsoluciones\Checkout\Model\DistritoFactory $distrito
    )
    {
        $this->departamentoFactory = $departamento;
        $this->provinciaFactory = $provincia;
        $this->distritoFactory = $distrito;
    }

    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        
        $departamentos =    [ 
            ["idDepa" => "2", "departamento" => "Alajuela", "pais" => "CR"],
            ["idDepa" => "3", "departamento" => "Cartago", "pais" => "CR"],
            ["idDepa" => "5", "departamento" => "Guanacaste", "pais" => "CR"],
            ["idDepa" => "4", "departamento" => "Heredia", "pais" => "CR"],
            ["idDepa" => "7", "departamento" => "Limón", "pais" => "CR"],
            ["idDepa" => "6", "departamento" => "Puntarenas", "pais" => "CR"],
            ["idDepa" => "1", "departamento" => "San José", "pais" => "CR"],
			
			
        ];

  $provincias =   [
			["idProv" => "1", "provincia" => "San Jose", "idDepa" => "1"],
            ["idProv" => "2", "provincia" => "Escazu", "idDepa" => "1"],
            ["idProv" => "3", "provincia" => "Desamparados", "idDepa" => "1"],
            ["idProv" => "4", "provincia" => "Puriscal", "idDepa" => "1"],
            ["idProv" => "5", "provincia" => "Tarrazu", "idDepa" => "1"],
            ["idProv" => "6", "provincia" => "Aserri", "idDepa" => "1"],
            ["idProv" => "7", "provincia" => "Mora", "idDepa" => "1"],
            ["idProv" => "8", "provincia" => "Goicoechea", "idDepa" => "1"],
            ["idProv" => "9", "provincia" => "Santa Ana", "idDepa" => "1"],
            ["idProv" => "10", "provincia" => "Alajuelita", "idDepa" => "1"],
            ["idProv" => "11", "provincia" => "Coronado", "idDepa" => "1"],
            ["idProv" => "12", "provincia" => "Acosta", "idDepa" => "1"],
            ["idProv" => "13", "provincia" => "Tibas", "idDepa" => "1"],
            ["idProv" => "14", "provincia" => "Moravia", "idDepa" => "1"],
            ["idProv" => "15", "provincia" => "Montes De Oca", "idDepa" => "1"],
            ["idProv" => "16", "provincia" => "Turrubares", "idDepa" => "1"],
            ["idProv" => "17", "provincia" => "Dota", "idDepa" => "1"],
            ["idProv" => "18", "provincia" => "Curridabat", "idDepa" => "1"],
            ["idProv" => "19", "provincia" => "Perez Zeledon", "idDepa" => "1"],
            ["idProv" => "20", "provincia" => "Leon Cortes", "idDepa" => "1"],
            ["idProv" => "21", "provincia" => "Alajuela", "idDepa" => "2"],
            ["idProv" => "22", "provincia" => "San Ramon", "idDepa" => "2"],
            ["idProv" => "23", "provincia" => "Grecia", "idDepa" => "2"],
            ["idProv" => "24", "provincia" => "San Mateo", "idDepa" => "2"],
            ["idProv" => "25", "provincia" => "Atenas", "idDepa" => "2"],
            ["idProv" => "26", "provincia" => "Naranjo", "idDepa" => "2"],
            ["idProv" => "27", "provincia" => "Palmares", "idDepa" => "2"],
            ["idProv" => "28", "provincia" => "Poas", "idDepa" => "2"],
            ["idProv" => "29", "provincia" => "Orotina", "idDepa" => "2"],
            ["idProv" => "30", "provincia" => "San Carlos", "idDepa" => "2"],
            ["idProv" => "31", "provincia" => "Alfaro Ruiz", "idDepa" => "2"],
            ["idProv" => "32", "provincia" => "Valverde Vega", "idDepa" => "2"],
            ["idProv" => "33", "provincia" => "Upala", "idDepa" => "2"],
            ["idProv" => "34", "provincia" => "Los Chiles", "idDepa" => "2"],
            ["idProv" => "35", "provincia" => "Guatuso", "idDepa" => "2"],
            ["idProv" => "36", "provincia" => "Rio Cuarto", "idDepa" => "2"],
            ["idProv" => "37", "provincia" => "Cartago", "idDepa" => "3"],
            ["idProv" => "38", "provincia" => "Paraiso", "idDepa" => "3"],
            ["idProv" => "39", "provincia" => "La Union", "idDepa" => "3"],
            ["idProv" => "40", "provincia" => "Jimenez", "idDepa" => "3"],
            ["idProv" => "41", "provincia" => "Turrialba", "idDepa" => "3"],
            ["idProv" => "42", "provincia" => "Alvarado", "idDepa" => "3"],
            ["idProv" => "43", "provincia" => "Oreamuno", "idDepa" => "3"],
            ["idProv" => "44", "provincia" => "El Guarco", "idDepa" => "3"],
            ["idProv" => "45", "provincia" => "Heredia", "idDepa" => "4"],
            ["idProv" => "46", "provincia" => "Barva", "idDepa" => "4"],
            ["idProv" => "47", "provincia" => "Santo Domingo", "idDepa" => "4"],
            ["idProv" => "48", "provincia" => "Santa Barbara", "idDepa" => "4"],
            ["idProv" => "49", "provincia" => "San Rafael", "idDepa" => "4"],
            ["idProv" => "50", "provincia" => "San Isidro", "idDepa" => "4"],
            ["idProv" => "51", "provincia" => "Belen", "idDepa" => "4"],
            ["idProv" => "52", "provincia" => "Flores", "idDepa" => "4"],
            ["idProv" => "53", "provincia" => "San Pablo", "idDepa" => "4"],
            ["idProv" => "54", "provincia" => "Sarapiqui", "idDepa" => "4"],
            ["idProv" => "55", "provincia" => "Liberia", "idDepa" => "5"],
            ["idProv" => "56", "provincia" => "Nicoya", "idDepa" => "5"],
            ["idProv" => "57", "provincia" => "Santa Cruz", "idDepa" => "5"],
            ["idProv" => "58", "provincia" => "Bagaces", "idDepa" => "5"],
            ["idProv" => "59", "provincia" => "Carrillo", "idDepa" => "5"],
            ["idProv" => "60", "provincia" => "Cañas", "idDepa" => "5"],
            ["idProv" => "61", "provincia" => "Abangares", "idDepa" => "5"],
            ["idProv" => "62", "provincia" => "Tilaran", "idDepa" => "5"],
            ["idProv" => "63", "provincia" => "Nandayure", "idDepa" => "5"],
            ["idProv" => "64", "provincia" => "La Cruz", "idDepa" => "5"],
            ["idProv" => "65", "provincia" => "Hojancha", "idDepa" => "5"],
            ["idProv" => "66", "provincia" => "Puntarenas", "idDepa" => "6"],
            ["idProv" => "67", "provincia" => "Esparza", "idDepa" => "6"],
            ["idProv" => "68", "provincia" => "Buenos Aires", "idDepa" => "6"],
            ["idProv" => "69", "provincia" => "Montes De Oro", "idDepa" => "6"],
            ["idProv" => "70", "provincia" => "Osa", "idDepa" => "6"],
            ["idProv" => "71", "provincia" => "Aguirre", "idDepa" => "6"],
            ["idProv" => "72", "provincia" => "Golfito", "idDepa" => "6"],
            ["idProv" => "73", "provincia" => "Coto Brus", "idDepa" => "6"],
            ["idProv" => "74", "provincia" => "Parrita", "idDepa" => "6"],
            ["idProv" => "75", "provincia" => "Corredores", "idDepa" => "6"],
            ["idProv" => "76", "provincia" => "Garabito", "idDepa" => "6"],
            ["idProv" => "77", "provincia" => "Limon", "idDepa" => "7"],
            ["idProv" => "78", "provincia" => "Pococi", "idDepa" => "7"],
            ["idProv" => "79", "provincia" => "Siquirres", "idDepa" => "7"],
            ["idProv" => "80", "provincia" => "Talamanca", "idDepa" => "7"],
            ["idProv" => "81", "provincia" => "Matina", "idDepa" => "7"],
            ["idProv" => "82", "provincia" => "Guacimo", "idDepa" => "7"]

        ];

        $distritos =    [ 
            ["idDist" => "10101", "distrito" => "Carmen", "idProv" => "1"],
            ["idDist" => "10102", "distrito" => "Merced", "idProv" => "1"],
            ["idDist" => "10103", "distrito" => "Hospital", "idProv" => "1"],
            ["idDist" => "10104", "distrito" => "Catedral", "idProv" => "1"],
            ["idDist" => "10105", "distrito" => "Zapote", "idProv" => "1"],
            ["idDist" => "10106", "distrito" => "San Francisco de Dos Ríos", "idProv" => "1"],
            ["idDist" => "10107", "distrito" => "Uruca", "idProv" => "1"],
            ["idDist" => "10108", "distrito" => "Mata Redonda", "idProv" => "1"],
            ["idDist" => "10109", "distrito" => "Pavas", "idProv" => "1"],
            ["idDist" => "10110", "distrito" => "Hatillo", "idProv" => "1"],
            ["idDist" => "10111", "distrito" => "San Sebastián", "idProv" => "1"],
            ["idDist" => "10201", "distrito" => "Escazú", "idProv" => "2"],
            ["idDist" => "10202", "distrito" => "San Antonio", "idProv" => "2"],
            ["idDist" => "10203", "distrito" => "San Rafael", "idProv" => "2"],
            ["idDist" => "10301", "distrito" => "Desamparados", "idProv" => "3"],
            ["idDist" => "10302", "distrito" => "San Miguel", "idProv" => "3"],
            ["idDist" => "10303", "distrito" => "San Juan de Dios", "idProv" => "3"],
            ["idDist" => "10304", "distrito" => "San Rafael Arriba", "idProv" => "3"],
            ["idDist" => "10305", "distrito" => "San Antonio", "idProv" => "3"],
            ["idDist" => "10306", "distrito" => "Frailes", "idProv" => "3"],
            ["idDist" => "10307", "distrito" => "Patarra", "idProv" => "3"],
            ["idDist" => "10308", "distrito" => "San Cristobal", "idProv" => "3"],
            ["idDist" => "10309", "distrito" => "Rosario", "idProv" => "3"],
            ["idDist" => "10310", "distrito" => "Damas", "idProv" => "3"],
            ["idDist" => "10311", "distrito" => "San Rafael Abajo", "idProv" => "3"],
            ["idDist" => "10312", "distrito" => "Gravilias", "idProv" => "3"],
            ["idDist" => "10313", "distrito" => "Los Guido", "idProv" => "3"],
            ["idDist" => "10401", "distrito" => "Santiago", "idProv" => "4"],
            ["idDist" => "10402", "distrito" => "Mercedes Sur", "idProv" => "4"],
            ["idDist" => "10403", "distrito" => "Barbacoas", "idProv" => "4"],
            ["idDist" => "10404", "distrito" => "Grifo Alto", "idProv" => "4"],
            ["idDist" => "10405", "distrito" => "San Rafael", "idProv" => "4"],
            ["idDist" => "10406", "distrito" => "Candelaria", "idProv" => "4"],
            ["idDist" => "10407", "distrito" => "Desamparaditos", "idProv" => "4"],
            ["idDist" => "10408", "distrito" => "San Antonio", "idProv" => "4"],
            ["idDist" => "10409", "distrito" => "Chires", "idProv" => "4"],
            ["idDist" => "10501", "distrito" => "San Marcos", "idProv" => "5"],
            ["idDist" => "10502", "distrito" => "San Lorenzo", "idProv" => "5"],
            ["idDist" => "10503", "distrito" => "San Carlos", "idProv" => "5"],
            ["idDist" => "10601", "distrito" => "Aserrí", "idProv" => "6"],
            ["idDist" => "10602", "distrito" => "Tarbaca o Praga", "idProv" => "6"],
            ["idDist" => "10603", "distrito" => "Vuelta de Jorco", "idProv" => "6"],
            ["idDist" => "10604", "distrito" => "San Gabriel", "idProv" => "6"],
            ["idDist" => "10605", "distrito" => "La Legua", "idProv" => "6"],
            ["idDist" => "10606", "distrito" => "Monterrey", "idProv" => "6"],
            ["idDist" => "10607", "distrito" => "Salitrillos", "idProv" => "6"],
            ["idDist" => "10701", "distrito" => "Colón", "idProv" => "7"],
            ["idDist" => "10702", "distrito" => "Guayabo", "idProv" => "7"],
            ["idDist" => "10703", "distrito" => "Tabarcia", "idProv" => "7"],
            ["idDist" => "10704", "distrito" => "Piedras Negras", "idProv" => "7"],
            ["idDist" => "10705", "distrito" => "Picagres", "idProv" => "7"],
            ["idDist" => "10801", "distrito" => "Guadalupe", "idProv" => "8"],
            ["idDist" => "10802", "distrito" => "San Francisco", "idProv" => "8"],
            ["idDist" => "10803", "distrito" => "Calle Blancos", "idProv" => "8"],
            ["idDist" => "10804", "distrito" => "Mata de Plátano", "idProv" => "8"],
            ["idDist" => "10805", "distrito" => "Ipís", "idProv" => "8"],
            ["idDist" => "10806", "distrito" => "Rancho Redondo", "idProv" => "8"],
            ["idDist" => "10807", "distrito" => "Purral", "idProv" => "8"],
            ["idDist" => "10901", "distrito" => "Santa Ana", "idProv" => "9"],
            ["idDist" => "10902", "distrito" => "Salitral", "idProv" => "9"],
            ["idDist" => "10903", "distrito" => "Pozos o Concepción", "idProv" => "9"],
            ["idDist" => "10904", "distrito" => "Uruca o San Joaquín", "idProv" => "9"],
            ["idDist" => "10905", "distrito" => "Piedades", "idProv" => "9"],
            ["idDist" => "10906", "distrito" => "Brasil", "idProv" => "9"],
            ["idDist" => "11001", "distrito" => "Alajuelita", "idProv" => "10"],
            ["idDist" => "11002", "distrito" => "San Josecito", "idProv" => "10"],
            ["idDist" => "11003", "distrito" => "San Antonio", "idProv" => "10"],
            ["idDist" => "11004", "distrito" => "Concepción", "idProv" => "10"],
            ["idDist" => "11005", "distrito" => "San Felipe", "idProv" => "10"],
            ["idDist" => "11101", "distrito" => "San Isidro", "idProv" => "11"],
            ["idDist" => "11102", "distrito" => "San Rafael", "idProv" => "11"],
            ["idDist" => "11103", "distrito" => "Dulce Nombre o Jesús", "idProv" => "11"],
            ["idDist" => "11104", "distrito" => "Patalillo", "idProv" => "11"],
            ["idDist" => "11105", "distrito" => "Cascajal", "idProv" => "11"],
            ["idDist" => "11201", "distrito" => "San Ignacio", "idProv" => "12"],
            ["idDist" => "11202", "distrito" => "Guaitil", "idProv" => "12"],
            ["idDist" => "11203", "distrito" => "Palmichal", "idProv" => "12"],
            ["idDist" => "11204", "distrito" => "Cangrejal", "idProv" => "12"],
            ["idDist" => "11205", "distrito" => "Sabanillas", "idProv" => "12"],
            ["idDist" => "11301", "distrito" => "San Juan", "idProv" => "13"],
            ["idDist" => "11302", "distrito" => "Cinco Esquinas", "idProv" => "13"],
            ["idDist" => "11303", "distrito" => "Anselmo Llorente", "idProv" => "13"],
            ["idDist" => "11304", "distrito" => "León XIII", "idProv" => "13"],
            ["idDist" => "11305", "distrito" => "Colima", "idProv" => "13"],
            ["idDist" => "11401", "distrito" => "San Vicente", "idProv" => "14"],
            ["idDist" => "11402", "distrito" => "San Jerónimo", "idProv" => "14"],
            ["idDist" => "11403", "distrito" => "La Trinidad", "idProv" => "14"],
            ["idDist" => "11501", "distrito" => "San Pedro", "idProv" => "15"],
            ["idDist" => "11502", "distrito" => "Sabanilla", "idProv" => "15"],
            ["idDist" => "11503", "distrito" => "Mercedes o Betania", "idProv" => "15"],
            ["idDist" => "11504", "distrito" => "San Rafael", "idProv" => "15"],
            ["idDist" => "11601", "distrito" => "San Pablo", "idProv" => "16"],
            ["idDist" => "11602", "distrito" => "San Pedro", "idProv" => "16"],
            ["idDist" => "11603", "distrito" => "San Juan de Mata", "idProv" => "16"],
            ["idDist" => "11604", "distrito" => "San Luis", "idProv" => "16"],
            ["idDist" => "11605", "distrito" => "Carara", "idProv" => "16"],
            ["idDist" => "11701", "distrito" => "Santa María", "idProv" => "17"],
            ["idDist" => "11702", "distrito" => "Jardín", "idProv" => "17"],
            ["idDist" => "11703", "distrito" => "Copey", "idProv" => "17"],
            ["idDist" => "11801", "distrito" => "Curridabat", "idProv" => "18"],
            ["idDist" => "11802", "distrito" => "Granadilla", "idProv" => "18"],
            ["idDist" => "11803", "distrito" => "Sánchez", "idProv" => "18"],
            ["idDist" => "11804", "distrito" => "Tirrases", "idProv" => "18"],
            ["idDist" => "11901", "distrito" => "San Isidro de El General", "idProv" => "19"],
            ["idDist" => "11902", "distrito" => "General", "idProv" => "19"],
            ["idDist" => "11903", "distrito" => "Daniel Flores", "idProv" => "19"],
            ["idDist" => "11904", "distrito" => "Rivas", "idProv" => "19"],
            ["idDist" => "11905", "distrito" => "San Pedro", "idProv" => "19"],
            ["idDist" => "11906", "distrito" => "Platanares", "idProv" => "19"],
            ["idDist" => "11907", "distrito" => "Pejibaye", "idProv" => "19"],
            ["idDist" => "11908", "distrito" => "Cajón o Carmen", "idProv" => "19"],
            ["idDist" => "11909", "distrito" => "Barú", "idProv" => "19"],
            ["idDist" => "11910", "distrito" => "Río Nuevo", "idProv" => "19"],
            ["idDist" => "11911", "distrito" => "Páramo", "idProv" => "19"],
            ["idDist" => "12001", "distrito" => "San Pablo", "idProv" => "20"],
            ["idDist" => "12002", "distrito" => "San Andrés", "idProv" => "20"],
            ["idDist" => "12003", "distrito" => "Llano Bonito", "idProv" => "20"],
            ["idDist" => "12004", "distrito" => "San Isidro", "idProv" => "20"],
            ["idDist" => "12005", "distrito" => "Santa Cruz", "idProv" => "20"],
            ["idDist" => "12006", "distrito" => "San Antonio", "idProv" => "20"],
            ["idDist" => "20101", "distrito" => "Alajuela", "idProv" => "21"],
            ["idDist" => "20102", "distrito" => "San José", "idProv" => "21"],
            ["idDist" => "20103", "distrito" => "Carrizal", "idProv" => "21"],
            ["idDist" => "20104", "distrito" => "San Antonio", "idProv" => "21"],
            ["idDist" => "20105", "distrito" => "Guácima", "idProv" => "21"],
            ["idDist" => "20106", "distrito" => "San Isidro", "idProv" => "21"],
            ["idDist" => "20107", "distrito" => "Sabanilla", "idProv" => "21"],
            ["idDist" => "20108", "distrito" => "San Rafael", "idProv" => "21"],
            ["idDist" => "20109", "distrito" => "Río Segundo", "idProv" => "21"],
            ["idDist" => "20110", "distrito" => "Desamparados", "idProv" => "21"],
            ["idDist" => "20111", "distrito" => "Turrucares", "idProv" => "21"],
            ["idDist" => "20112", "distrito" => "Tambor", "idProv" => "21"],
            ["idDist" => "20113", "distrito" => "La Garita", "idProv" => "21"],
            ["idDist" => "20114", "distrito" => "Sarapiquí", "idProv" => "21"],
            ["idDist" => "20201", "distrito" => "San Ramón", "idProv" => "22"],
            ["idDist" => "20202", "distrito" => "Santiago", "idProv" => "22"],
            ["idDist" => "20203", "distrito" => "San Juan", "idProv" => "22"],
            ["idDist" => "20204", "distrito" => "Piedades Norte", "idProv" => "22"],
            ["idDist" => "20205", "distrito" => "Piedades Sur", "idProv" => "22"],
            ["idDist" => "20206", "distrito" => "San Rafael", "idProv" => "22"],
            ["idDist" => "20207", "distrito" => "San Isidro", "idProv" => "22"],
            ["idDist" => "20208", "distrito" => "Angeles", "idProv" => "22"],
            ["idDist" => "20209", "distrito" => "Alfaro", "idProv" => "22"],
            ["idDist" => "20210", "distrito" => "Volio", "idProv" => "22"],
            ["idDist" => "20211", "distrito" => "Concepción", "idProv" => "22"],
            ["idDist" => "20212", "distrito" => "Zapotal", "idProv" => "22"],
            ["idDist" => "20213", "distrito" => "San Isidro de Peñas Blancas", "idProv" => "22"],
            ["idDist" => "20301", "distrito" => "Grecia", "idProv" => "23"],
            ["idDist" => "20302", "distrito" => "San Isidro", "idProv" => "23"],
            ["idDist" => "20303", "distrito" => "San José", "idProv" => "23"],
            ["idDist" => "20304", "distrito" => "San Roque", "idProv" => "23"],
            ["idDist" => "20305", "distrito" => "Tacares", "idProv" => "23"],
			["idDist" => "20306", "distrito" => "Río Cuarto", "idProv" => "23"],
            ["idDist" => "20307", "distrito" => "Puente Piedra", "idProv" => "23"],
            ["idDist" => "20308", "distrito" => "Bolívar", "idProv" => "23"],
            ["idDist" => "20401", "distrito" => "San Mateo", "idProv" => "24"],
            ["idDist" => "20402", "distrito" => "Desmonte", "idProv" => "24"],
            ["idDist" => "20403", "distrito" => "Jesús María", "idProv" => "24"],
            ["idDist" => "20501", "distrito" => "Atenas", "idProv" => "25"],
            ["idDist" => "20502", "distrito" => "Jesús", "idProv" => "25"],
            ["idDist" => "20503", "distrito" => "Mercedes", "idProv" => "25"],
            ["idDist" => "20504", "distrito" => "San Isidro", "idProv" => "25"],
            ["idDist" => "20505", "distrito" => "Concepción", "idProv" => "25"],
            ["idDist" => "20506", "distrito" => "San José", "idProv" => "25"],
            ["idDist" => "20507", "distrito" => "Santa Eulalia", "idProv" => "25"],
            ["idDist" => "20508", "distrito" => "Escobal", "idProv" => "25"],
            ["idDist" => "20601", "distrito" => "Naranjo", "idProv" => "26"],
            ["idDist" => "20602", "distrito" => "San Miguel", "idProv" => "26"],
            ["idDist" => "20603", "distrito" => "San José", "idProv" => "26"],
            ["idDist" => "20604", "distrito" => "Cirrí Sur", "idProv" => "26"],
            ["idDist" => "20605", "distrito" => "San Jerónimo", "idProv" => "26"],
            ["idDist" => "20606", "distrito" => "San Juan", "idProv" => "26"],
            ["idDist" => "20607", "distrito" => "Rosario", "idProv" => "26"],
			["idDist" => "20608", "distrito" => "Palmitos", "idProv" => "26"],
            ["idDist" => "20701", "distrito" => "Palmares", "idProv" => "27"],
            ["idDist" => "20702", "distrito" => "Zaragoza", "idProv" => "27"],
            ["idDist" => "20703", "distrito" => "Buenos Aires", "idProv" => "27"],
            ["idDist" => "20704", "distrito" => "Santiago", "idProv" => "27"],
            ["idDist" => "20705", "distrito" => "Candelaria", "idProv" => "27"],
            ["idDist" => "20706", "distrito" => "Esquipulas", "idProv" => "27"],
            ["idDist" => "20707", "distrito" => "La Granja", "idProv" => "27"],
            ["idDist" => "20801", "distrito" => "San Pedro", "idProv" => "28"],
            ["idDist" => "20802", "distrito" => "San Juan", "idProv" => "28"],
            ["idDist" => "20803", "distrito" => "San Rafael", "idProv" => "28"],
            ["idDist" => "20804", "distrito" => "Carrillos", "idProv" => "28"],
            ["idDist" => "20805", "distrito" => "Sabana Redonda", "idProv" => "28"],
            ["idDist" => "20901", "distrito" => "Orotina", "idProv" => "29"],
            ["idDist" => "20902", "distrito" => "Mastate", "idProv" => "29"],
            ["idDist" => "20903", "distrito" => "Hacienda Vieja", "idProv" => "29"],
            ["idDist" => "20904", "distrito" => "Coyolar", "idProv" => "29"],
            ["idDist" => "20905", "distrito" => "Ceiba", "idProv" => "29"],
            ["idDist" => "21001", "distrito" => "Quesada", "idProv" => "30"],
            ["idDist" => "21002", "distrito" => "Florencia", "idProv" => "30"],
            ["idDist" => "21003", "distrito" => "Buenavista", "idProv" => "30"],
            ["idDist" => "21004", "distrito" => "Aguas Zarcas", "idProv" => "30"],
            ["idDist" => "21005", "distrito" => "Venecia", "idProv" => "30"],
            ["idDist" => "21006", "distrito" => "Pital", "idProv" => "30"],
            ["idDist" => "21007", "distrito" => "Fortuna", "idProv" => "30"],
            ["idDist" => "21008", "distrito" => "Tigra", "idProv" => "30"],
            ["idDist" => "21009", "distrito" => "Palmera", "idProv" => "30"],
            ["idDist" => "21010", "distrito" => "Venado", "idProv" => "30"],
            ["idDist" => "21011", "distrito" => "Cutris", "idProv" => "30"],
            ["idDist" => "21012", "distrito" => "Monterrey", "idProv" => "30"],
            ["idDist" => "21013", "distrito" => "Pocosol", "idProv" => "30"],
            ["idDist" => "21101", "distrito" => "Zarcero", "idProv" => "31"],
            ["idDist" => "21102", "distrito" => "Laguna", "idProv" => "31"],
            ["idDist" => "21103", "distrito" => "Tapezco", "idProv" => "31"],
            ["idDist" => "21104", "distrito" => "Guadalupe", "idProv" => "31"],
            ["idDist" => "21105", "distrito" => "Palmira", "idProv" => "31"],
            ["idDist" => "21106", "distrito" => "Zapote", "idProv" => "31"],
            ["idDist" => "21107", "distrito" => "Brisas", "idProv" => "31"],
            ["idDist" => "21201", "distrito" => "Sarchí Norte", "idProv" => "32"],
            ["idDist" => "21202", "distrito" => "Sarchí Sur", "idProv" => "32"],
            ["idDist" => "21203", "distrito" => "Toro Amarillo", "idProv" => "32"],
            ["idDist" => "21204", "distrito" => "San Pedro", "idProv" => "32"],
            ["idDist" => "21205", "distrito" => "Rodríguez", "idProv" => "32"],
            ["idDist" => "21301", "distrito" => "Upala", "idProv" => "33"],
            ["idDist" => "21302", "distrito" => "Aguas Claras", "idProv" => "33"],
            ["idDist" => "21303", "distrito" => "San José o Pizote", "idProv" => "33"],
            ["idDist" => "21304", "distrito" => "Bijagua", "idProv" => "33"],
            ["idDist" => "21305", "distrito" => "Delicias", "idProv" => "33"],
            ["idDist" => "21306", "distrito" => "Dos Ríos", "idProv" => "33"],
            ["idDist" => "21307", "distrito" => "Yoliyllal", "idProv" => "33"],
            ["idDist" => "21401", "distrito" => "Los Chiles", "idProv" => "34"],
            ["idDist" => "21402", "distrito" => "Caño Negro", "idProv" => "34"],
            ["idDist" => "21403", "distrito" => "Amparo", "idProv" => "34"],
            ["idDist" => "21404", "distrito" => "San Jorge", "idProv" => "34"],
            ["idDist" => "21501", "distrito" => "San Rafael", "idProv" => "35"],
            ["idDist" => "21502", "distrito" => "Buenavista", "idProv" => "35"],
            ["idDist" => "21503", "distrito" => "Cote", "idProv" => "35"],
            ["idDist" => "21504", "distrito" => "Katira", "idProv" => "35"],
            ["idDist" => "30101", "distrito" => "Oriental", "idProv" => "37"],
            ["idDist" => "30102", "distrito" => "Occidental", "idProv" => "37"],
            ["idDist" => "30103", "distrito" => "Carmen", "idProv" => "37"],
            ["idDist" => "30104", "distrito" => "San Nicolás", "idProv" => "37"],
            ["idDist" => "30105", "distrito" => "Aguacaliente (San Francisco);", "idProv" => "37"],
            ["idDist" => "30106", "distrito" => "Guadalupe (Arenilla);", "idProv" => "37"],
            ["idDist" => "30107", "distrito" => "Corralillo", "idProv" => "37"],
            ["idDist" => "30108", "distrito" => "Tierra Blanca", "idProv" => "37"],
            ["idDist" => "30109", "distrito" => "Dulce Nombre", "idProv" => "37"],
            ["idDist" => "30110", "distrito" => "Llano Grande", "idProv" => "37"],
            ["idDist" => "30111", "distrito" => "Quebradilla", "idProv" => "37"],
            ["idDist" => "30201", "distrito" => "Paraíso", "idProv" => "38"],
            ["idDist" => "30202", "distrito" => "Santiago", "idProv" => "38"],
            ["idDist" => "30203", "distrito" => "Orosi", "idProv" => "38"],
            ["idDist" => "30204", "distrito" => "Cachí", "idProv" => "38"],
            ["idDist" => "30205", "distrito" => "Llanos de Sta Lucia", "idProv" => "38"],
            ["idDist" => "30301", "distrito" => "Tres Ríos", "idProv" => "39"],
            ["idDist" => "30302", "distrito" => "San Diego", "idProv" => "39"],
            ["idDist" => "30303", "distrito" => "San Juan", "idProv" => "39"],
            ["idDist" => "30304", "distrito" => "San Rafael", "idProv" => "39"],
            ["idDist" => "30305", "distrito" => "Concepción", "idProv" => "39"],
            ["idDist" => "30306", "distrito" => "Dulce Nombre", "idProv" => "39"],
            ["idDist" => "30307", "distrito" => "San Ramón", "idProv" => "39"],
            ["idDist" => "30308", "distrito" => "Río Azul", "idProv" => "39"],
            ["idDist" => "30401", "distrito" => "Juan Viñas", "idProv" => "40"],
            ["idDist" => "30402", "distrito" => "Tucurrique", "idProv" => "40"],
            ["idDist" => "30403", "distrito" => "Pejibaye", "idProv" => "40"],
            ["idDist" => "30501", "distrito" => "Turrialba", "idProv" => "41"],
            ["idDist" => "30502", "distrito" => "La Suiza", "idProv" => "41"],
            ["idDist" => "30503", "distrito" => "Peralta", "idProv" => "41"],
            ["idDist" => "30504", "distrito" => "Santa Cruz", "idProv" => "41"],
            ["idDist" => "30505", "distrito" => "Santa Teresita", "idProv" => "41"],
            ["idDist" => "30506", "distrito" => "Pavones", "idProv" => "41"],
            ["idDist" => "30507", "distrito" => "Tuis", "idProv" => "41"],
            ["idDist" => "30508", "distrito" => "Tayutic", "idProv" => "41"],
            ["idDist" => "30509", "distrito" => "Santa Rosa", "idProv" => "41"],
            ["idDist" => "30510", "distrito" => "Tres Equis", "idProv" => "41"],
            ["idDist" => "30511", "distrito" => "La Isabel", "idProv" => "41"],
            ["idDist" => "30512", "distrito" => "Chirripo", "idProv" => "41"],
            ["idDist" => "30601", "distrito" => "Pacayas", "idProv" => "42"],
            ["idDist" => "30602", "distrito" => "Cervantes", "idProv" => "42"],
            ["idDist" => "30603", "distrito" => "Capellades", "idProv" => "42"],
            ["idDist" => "30701", "distrito" => "San Rafael", "idProv" => "43"],
            ["idDist" => "30702", "distrito" => "Cot", "idProv" => "43"],
            ["idDist" => "30703", "distrito" => "Potrero Cerrado", "idProv" => "43"],
            ["idDist" => "30704", "distrito" => "Cipreses", "idProv" => "43"],
            ["idDist" => "30705", "distrito" => "Santa Rosa", "idProv" => "43"],
            ["idDist" => "30801", "distrito" => "El Tejar", "idProv" => "44"],
            ["idDist" => "30802", "distrito" => "San Isidro", "idProv" => "44"],
            ["idDist" => "30803", "distrito" => "Tobosi", "idProv" => "44"],
            ["idDist" => "30804", "distrito" => "Patio de Agua", "idProv" => "44"],
            ["idDist" => "40101", "distrito" => "Heredia", "idProv" => "45"],
            ["idDist" => "40102", "distrito" => "Mercedes", "idProv" => "45"],
            ["idDist" => "40103", "distrito" => "San Francisco", "idProv" => "45"],
            ["idDist" => "40104", "distrito" => "Ulloa", "idProv" => "45"],
            ["idDist" => "40105", "distrito" => "Vara Blanca", "idProv" => "45"],
            ["idDist" => "40201", "distrito" => "Barva", "idProv" => "46"],
            ["idDist" => "40202", "distrito" => "San Pedro", "idProv" => "46"],
            ["idDist" => "40203", "distrito" => "San Pablo", "idProv" => "46"],
            ["idDist" => "40204", "distrito" => "San Roque", "idProv" => "46"],
            ["idDist" => "40205", "distrito" => "Santa Lucía", "idProv" => "46"],
            ["idDist" => "40206", "distrito" => "San José de la Montaña", "idProv" => "46"],
            ["idDist" => "40301", "distrito" => "Santo Domingo", "idProv" => "47"],
            ["idDist" => "40302", "distrito" => "San Vicente", "idProv" => "47"],
            ["idDist" => "40303", "distrito" => "San Miguel", "idProv" => "47"],
            ["idDist" => "40304", "distrito" => "Paracito", "idProv" => "47"],
            ["idDist" => "40305", "distrito" => "Santo Tomás", "idProv" => "47"],
            ["idDist" => "40306", "distrito" => "Santa Rosa", "idProv" => "47"],
            ["idDist" => "40307", "distrito" => "Tures", "idProv" => "47"],
            ["idDist" => "40308", "distrito" => "Pará", "idProv" => "47"],
            ["idDist" => "40401", "distrito" => "Santa Bárbara", "idProv" => "48"],
            ["idDist" => "40402", "distrito" => "San Pedro", "idProv" => "48"],
            ["idDist" => "40403", "distrito" => "San Juan", "idProv" => "48"],
            ["idDist" => "40404", "distrito" => "Jesús", "idProv" => "48"],
            ["idDist" => "40405", "distrito" => "Santo Domingo del Roble", "idProv" => "48"],
            ["idDist" => "40406", "distrito" => "Puraba", "idProv" => "48"],
            ["idDist" => "40501", "distrito" => "San Rafael", "idProv" => "49"],
            ["idDist" => "40502", "distrito" => "San Josecito", "idProv" => "49"],
            ["idDist" => "40503", "distrito" => "Santiago", "idProv" => "49"],
            ["idDist" => "40504", "distrito" => "Angeles", "idProv" => "49"],
            ["idDist" => "40505", "distrito" => "Concepción", "idProv" => "49"],
            ["idDist" => "40601", "distrito" => "San Isidro", "idProv" => "50"],
            ["idDist" => "40602", "distrito" => "San José", "idProv" => "50"],
            ["idDist" => "40603", "distrito" => "Concepción", "idProv" => "50"],
            ["idDist" => "40604", "distrito" => "San Francisco", "idProv" => "50"],
            ["idDist" => "40701", "distrito" => "San Antonio", "idProv" => "51"],
            ["idDist" => "40702", "distrito" => "La Rivera", "idProv" => "51"],
            ["idDist" => "40703", "distrito" => "Asunción", "idProv" => "51"],
            ["idDist" => "40801", "distrito" => "San Joaquín", "idProv" => "52"],
            ["idDist" => "40802", "distrito" => "Barrantes", "idProv" => "52"],
            ["idDist" => "40803", "distrito" => "Llorente", "idProv" => "52"],
            ["idDist" => "40901", "distrito" => "San Pablo", "idProv" => "53"],
            ["idDist" => "40902", "distrito" => "Rincon de Sabanilla", "idProv" => "53"],
            ["idDist" => "41001", "distrito" => "Puerto Viejo", "idProv" => "54"],
            ["idDist" => "41002", "distrito" => "La Virgen", "idProv" => "54"],
            ["idDist" => "41003", "distrito" => "Horquetas", "idProv" => "54"],
            ["idDist" => "41004", "distrito" => "Llanuras del Gaspar", "idProv" => "54"],
            ["idDist" => "41005", "distrito" => "Cureña", "idProv" => "54"],
            ["idDist" => "50101", "distrito" => "Liberia", "idProv" => "55"],
            ["idDist" => "50102", "distrito" => "Cañas Dulces", "idProv" => "55"],
            ["idDist" => "50103", "distrito" => "Mayorga", "idProv" => "55"],
            ["idDist" => "50104", "distrito" => "Nacascolo", "idProv" => "55"],
            ["idDist" => "50105", "distrito" => "Curubande", "idProv" => "55"],
            ["idDist" => "50201", "distrito" => "Nicoya", "idProv" => "56"],
            ["idDist" => "50202", "distrito" => "Mansión", "idProv" => "56"],
            ["idDist" => "50203", "distrito" => "San Antonio", "idProv" => "56"],
            ["idDist" => "50204", "distrito" => "Quebrada Honda", "idProv" => "56"],
            ["idDist" => "50205", "distrito" => "Sámara", "idProv" => "56"],
            ["idDist" => "50206", "distrito" => "Nosara", "idProv" => "56"],
            ["idDist" => "50207", "distrito" => "Belén de Nosarita", "idProv" => "56"],
            ["idDist" => "50301", "distrito" => "Santa Cruz", "idProv" => "57"],
            ["idDist" => "50302", "distrito" => "Bolsón", "idProv" => "57"],
            ["idDist" => "50303", "distrito" => "Veintisiete de Abril", "idProv" => "57"],
            ["idDist" => "50304", "distrito" => "Tempate", "idProv" => "57"],
            ["idDist" => "50305", "distrito" => "Cartagena", "idProv" => "57"],
            ["idDist" => "50306", "distrito" => "Cuajiniquil", "idProv" => "57"],
            ["idDist" => "50307", "distrito" => "Diriá", "idProv" => "57"],
            ["idDist" => "50308", "distrito" => "Cabo Velas", "idProv" => "57"],
            ["idDist" => "50309", "distrito" => "Tamarindo", "idProv" => "57"],
            ["idDist" => "50401", "distrito" => "Bagaces", "idProv" => "58"],
            ["idDist" => "50402", "distrito" => "Fortuna", "idProv" => "58"],
            ["idDist" => "50403", "distrito" => "Mogote", "idProv" => "58"],
            ["idDist" => "50404", "distrito" => "Río Naranjo", "idProv" => "58"],
            ["idDist" => "50501", "distrito" => "Filadelfia", "idProv" => "59"],
            ["idDist" => "50502", "distrito" => "Palmira", "idProv" => "59"],
            ["idDist" => "50503", "distrito" => "Sardinal", "idProv" => "59"],
            ["idDist" => "50504", "distrito" => "Belén", "idProv" => "59"],
            ["idDist" => "50601", "distrito" => "Cañas", "idProv" => "60"],
            ["idDist" => "50602", "distrito" => "Palmira", "idProv" => "60"],
            ["idDist" => "50603", "distrito" => "San Miguel", "idProv" => "60"],
            ["idDist" => "50604", "distrito" => "Bebedero", "idProv" => "60"],
            ["idDist" => "50605", "distrito" => "Porozal", "idProv" => "60"],
            ["idDist" => "50701", "distrito" => "Juntas", "idProv" => "61"],
            ["idDist" => "50702", "distrito" => "Sierra", "idProv" => "61"],
            ["idDist" => "50703", "distrito" => "San Juan", "idProv" => "61"],
            ["idDist" => "50704", "distrito" => "Colorado", "idProv" => "61"],
            ["idDist" => "50801", "distrito" => "Tilarán", "idProv" => "62"],
            ["idDist" => "50802", "distrito" => "Quebrada Grande", "idProv" => "62"],
            ["idDist" => "50803", "distrito" => "Tronadora", "idProv" => "62"],
            ["idDist" => "50804", "distrito" => "Santa Rosa", "idProv" => "62"],
            ["idDist" => "50805", "distrito" => "Líbano", "idProv" => "62"],
            ["idDist" => "50806", "distrito" => "Tierras Morenas", "idProv" => "62"],
            ["idDist" => "50807", "distrito" => "Arenal", "idProv" => "62"],
            ["idDist" => "50901", "distrito" => "Carmona", "idProv" => "63"],
            ["idDist" => "50902", "distrito" => "Santa Rita", "idProv" => "63"],
            ["idDist" => "50903", "distrito" => "Zapotal", "idProv" => "63"],
            ["idDist" => "50904", "distrito" => "San Pablo", "idProv" => "63"],
            ["idDist" => "50905", "distrito" => "Porvenir", "idProv" => "63"],
            ["idDist" => "50906", "distrito" => "Bejuco", "idProv" => "63"],
            ["idDist" => "51001", "distrito" => "La Cruz", "idProv" => "64"],
            ["idDist" => "51002", "distrito" => "Santa Cecilia", "idProv" => "64"],
            ["idDist" => "51003", "distrito" => "Garita", "idProv" => "64"],
            ["idDist" => "51004", "distrito" => "Santa Elena", "idProv" => "64"],
            ["idDist" => "51101", "distrito" => "Hojancha", "idProv" => "65"],
            ["idDist" => "51102", "distrito" => "Monte Romo", "idProv" => "65"],
            ["idDist" => "51103", "distrito" => "Puerto Carrillo", "idProv" => "65"],
            ["idDist" => "51104", "distrito" => "Huacas", "idProv" => "65"],
            ["idDist" => "60101", "distrito" => "Puntarenas", "idProv" => "66"],
            ["idDist" => "60102", "distrito" => "Pitahaya", "idProv" => "66"],
            ["idDist" => "60103", "distrito" => "Chomes", "idProv" => "66"],
            ["idDist" => "60104", "distrito" => "Lepanto", "idProv" => "66"],
            ["idDist" => "60105", "distrito" => "Paquera", "idProv" => "66"],
            ["idDist" => "60106", "distrito" => "Manzanillo", "idProv" => "66"],
            ["idDist" => "60107", "distrito" => "Guacimal", "idProv" => "66"],
            ["idDist" => "60108", "distrito" => "Barranca", "idProv" => "66"],
            ["idDist" => "60109", "distrito" => "Monte Verde", "idProv" => "66"],
            ["idDist" => "60110", "distrito" => "Isla del Coco", "idProv" => "66"],
            ["idDist" => "60111", "distrito" => "Cóbano", "idProv" => "66"],
            ["idDist" => "60112", "distrito" => "Chacarita", "idProv" => "66"],
            ["idDist" => "60113", "distrito" => "Chira (Isla);", "idProv" => "66"],
            ["idDist" => "60114", "distrito" => "Acapulco", "idProv" => "66"],
            ["idDist" => "60115", "distrito" => "El Roble", "idProv" => "66"],
            ["idDist" => "60116", "distrito" => "Arancibia", "idProv" => "66"],
            ["idDist" => "60201", "distrito" => "Espíritu Santo", "idProv" => "67"],
            ["idDist" => "60202", "distrito" => "San Juan Grande", "idProv" => "67"],
            ["idDist" => "60203", "distrito" => "Macacona", "idProv" => "67"],
            ["idDist" => "60204", "distrito" => "San Rafael", "idProv" => "67"],
            ["idDist" => "60205", "distrito" => "San Jerónimo", "idProv" => "67"],
            ["idDist" => "60301", "distrito" => "Buenos Aires", "idProv" => "68"],
            ["idDist" => "60302", "distrito" => "Volcán", "idProv" => "68"],
            ["idDist" => "60303", "distrito" => "Potrero Grande", "idProv" => "68"],
            ["idDist" => "60304", "distrito" => "Boruca", "idProv" => "68"],
            ["idDist" => "60305", "distrito" => "Pilas", "idProv" => "68"],
            ["idDist" => "60306", "distrito" => "Colinas o Bajo de Maíz", "idProv" => "68"],
            ["idDist" => "60307", "distrito" => "Chánguena", "idProv" => "68"],
            ["idDist" => "60308", "distrito" => "Biolley", "idProv" => "68"],
            ["idDist" => "60309", "distrito" => "Brunka", "idProv" => "68"],
            ["idDist" => "60401", "distrito" => "Miramar", "idProv" => "69"],
            ["idDist" => "60402", "distrito" => "Unión", "idProv" => "69"],
            ["idDist" => "60403", "distrito" => "San Isidro", "idProv" => "69"],
            ["idDist" => "60501", "distrito" => "Puerto Cortés", "idProv" => "70"],
            ["idDist" => "60502", "distrito" => "Palmar", "idProv" => "70"],
            ["idDist" => "60503", "distrito" => "Sierpe", "idProv" => "70"],
            ["idDist" => "60504", "distrito" => "Bahía Ballena", "idProv" => "70"],
            ["idDist" => "60505", "distrito" => "Piedras Blancas", "idProv" => "70"],
            ["idDist" => "60601", "distrito" => "Quepos", "idProv" => "71"],
            ["idDist" => "60602", "distrito" => "Savegre", "idProv" => "71"],
            ["idDist" => "60603", "distrito" => "Naranjito", "idProv" => "71"],
            ["idDist" => "60701", "distrito" => "Golfito", "idProv" => "72"],
            ["idDist" => "60702", "distrito" => "Puerto Jiménez", "idProv" => "72"],
            ["idDist" => "60703", "distrito" => "Guaycará", "idProv" => "72"],
            ["idDist" => "60704", "distrito" => "Pavon", "idProv" => "72"],
            ["idDist" => "60801", "distrito" => "San Vito", "idProv" => "73"],
            ["idDist" => "60802", "distrito" => "Sabalito", "idProv" => "73"],
            ["idDist" => "60803", "distrito" => "Agua Buena", "idProv" => "73"],
            ["idDist" => "60804", "distrito" => "Limoncito", "idProv" => "73"],
            ["idDist" => "60805", "distrito" => "Pittier", "idProv" => "73"],
            ["idDist" => "60901", "distrito" => "Parrita", "idProv" => "74"],
            ["idDist" => "61001", "distrito" => "Corredor", "idProv" => "75"],
            ["idDist" => "61002", "distrito" => "La Cuesta", "idProv" => "75"],
            ["idDist" => "61003", "distrito" => "Paso Canoas", "idProv" => "75"],
            ["idDist" => "61004", "distrito" => "Laurel", "idProv" => "75"],
            ["idDist" => "61101", "distrito" => "Jacó", "idProv" => "76"],
            ["idDist" => "61102", "distrito" => "Tárcoles", "idProv" => "76"],
            ["idDist" => "70101", "distrito" => "Limón", "idProv" => "77"],
            ["idDist" => "70102", "distrito" => "Valle La Estrella", "idProv" => "77"],
            ["idDist" => "70103", "distrito" => "Río Blanco", "idProv" => "77"],
            ["idDist" => "70104", "distrito" => "Matama", "idProv" => "77"],
            ["idDist" => "70201", "distrito" => "Guápiles", "idProv" => "78"],
            ["idDist" => "70202", "distrito" => "Jiménez", "idProv" => "78"],
            ["idDist" => "70203", "distrito" => "Rita", "idProv" => "78"],
            ["idDist" => "70204", "distrito" => "Roxana", "idProv" => "78"],
            ["idDist" => "70205", "distrito" => "Cariari", "idProv" => "78"],
            ["idDist" => "70206", "distrito" => "Colorado", "idProv" => "78"],
            ["idDist" => "70301", "distrito" => "Siquirres", "idProv" => "79"],
            ["idDist" => "70302", "distrito" => "Pacuarito", "idProv" => "79"],
            ["idDist" => "70303", "distrito" => "Florida", "idProv" => "79"],
            ["idDist" => "70304", "distrito" => "Germania", "idProv" => "79"],
            ["idDist" => "70305", "distrito" => "Cairo", "idProv" => "79"],
            ["idDist" => "70306", "distrito" => "Alegría", "idProv" => "79"],
            ["idDist" => "70401", "distrito" => "Bratsi", "idProv" => "80"],
            ["idDist" => "70402", "distrito" => "Sixaola", "idProv" => "80"],
            ["idDist" => "70403", "distrito" => "Cahuita", "idProv" => "80"],
            ["idDist" => "70404", "distrito" => "Telire", "idProv" => "80"],
            ["idDist" => "70501", "distrito" => "Matina", "idProv" => "81"],
            ["idDist" => "70502", "distrito" => "Batán", "idProv" => "81"],
            ["idDist" => "70503", "distrito" => "Carrandí", "idProv" => "81"],
            ["idDist" => "70601", "distrito" => "Guácimo", "idProv" => "82"],
            ["idDist" => "70602", "distrito" => "Mercedes", "idProv" => "82"],
            ["idDist" => "70603", "distrito" => "Pocora", "idProv" => "82"],
            ["idDist" => "70604", "distrito" => "Río Jiménez", "idProv" => "82"],
            ["idDist" => "70605", "distrito" => "Duacarí", "idProv" => "82"],
        ];

        
        foreach ($departamentos as $key) {
            $this->departamentoFactory->create()->setData($key)->save();   
        }

        foreach ($provincias as $key) {
            $this->provinciaFactory->create()->setData($key)->save();   
        }

        foreach ($distritos as $key) {
            $this->distritoFactory->create()->setData($key)->save();   
        }
        
    }

}